# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.33
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: false
enable_checklog_odoo: true
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 17.0
org_name: MoonSun PTY LTD
org_slug: moonsunsoft
rebel_module_groups: []
repo_description: TODO, update the description in coper ansere file
repo_name: TODO, update the description in coper ansere file
repo_slug: TODO, update the description in coper ansere file
repo_website: https://www.moonsun.au/apps/integeration-toolbox
use_pyproject_toml: true
use_ruff: true

